name: build-docker-image

on:
  push:
    tags:
    - v**

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-musleabihf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install requirements
        run: |
          sudo apt-get update
          sudo apt-get -y install ca-certificates libssl-dev musl-tools
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: copy artifact
        run: |
          cp -r ./target/${{ matrix.target }}/release/tado-exporter ./
          chmod +x tado-exporter
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.arm
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tado-exporter:latest
          platforms: linux/arm/v7
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
